mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

    url(r'^portfolio/', include('portfolio.urls', namespace="portfolio")),
    url(r'^login', include('social.apps.django_app.urls', namespace="social")),
    url(r'^admin/', admin.site.urls),
]

portfolio/urls.py
from django.conf.urls import url

from . import views 

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^perso/', views.general, name='perso'),
        url(r'^education/(?P<pk>[0-9]+)/$', views.education, name='education'),
        url(r'^experience/(?P<pk>[0-9]+)/$', views.experience, name='experience'),
        url(r'^login/', views.login, name='login'),
        url(r'^logout/', views.logout, name='logout'),
        url(r'^show_personal/(?P<pk>[0-9]+)/$', views.show_personal,
            name='show_personal'),
        url(r'^show_education/(?P<pk>[0-9]+)/$', views.show_education,
            name='show_education'),
        url(r'^show_experience/(?P<pk>[0-9]+)/$', views.show_experience,
            name='show_experience'),
        url(r'^modify_perso/(?P<pk>[0-9]+)/$', views.modify_perso,
            name='modify_perso'),
        url(r'^modify_education/(?P<pk>[0-9]+)/$', views.modify_education,
            name='modify_education'),
        url(r'^modify_experience/(?P<pk>[0-9]+)/$', views.modify_experience, name='modify_experience'),
        url(r'^last_step/', views.last_step,
            name='last_step'),
        url(r'^upload_picture/', views.upload_picture,
            name='upload_picture'),
        url(r'^first_template/', views.first_template,
            name='first_template'),
        ]

portfolio/models.py
from django.db import models
from django.contrib.auth.models import User


class ImageModel(models.Model):
    pic = models.ImageField(upload_to = 'documents/')

class Experience(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    year = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=100)


class Personal(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    cover = models.TextField(max_length=600)
    

class Education(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    year = models.CharField(max_length=100)
    title = models.CharField(max_length=100)
    desc = models.TextField(max_length=500)

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from . import models as m
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm

class ImageUploadForm(forms.Form):
    image = forms.FileField(label="Select a file")
 
class UserForm(AuthenticationForm):
    class Meta:
        model = User 
        fields = ['username', 'password'] 


class PersoForm(ModelForm):
    class Meta:
        model = m.Personal
        fields = ['name', 'status', 'address', 'email', 'phone', 'cover']
 
class EducationForm(ModelForm):
    class Meta:
        model = m.Education
        fields = ['year', 'title', 'desc']
    
class ExperienceForm(ModelForm):
    class Meta:
        model = m.Experience
        fields = ['year', 'title', 'desc']
 

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.http import HttpResponse, HttpResponseForbidden
from django.contrib.auth import logout as logout_auth
from django.contrib.auth import login as login_auth
from .models import Personal, Education, Experience, ImageModel
from .forms import PersoForm, UserForm, EducationForm, ExperienceForm, ImageUploadForm
from django.contrib.auth import authenticate
from django.contrib.auth.models import User


def index(request):
    return render(request, 'base.html') 


def login(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        new_user = authenticate(username=username, password=password)
        if new_user is not None:
            login_auth(request, new_user)
            return HttpResponseRedirect(reverse('portfolio:perso'))
    else:
        form = UserForm()
        return render(request, 'login.html', {'form': form})

@login_required
def logout(request):
    logout_auth(request)
    return HttpResponseRedirect('/portfolio')

@login_required
def general(request):
    if request.method == 'POST':
        form = PersoForm(request.POST) 
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            phone = form.cleaned_data['phone']
            status = form.cleaned_data['status']
            address = form.cleaned_data['address']
            cover = form.cleaned_data['cover']
            
            perso = Personal.objects.create(name=name, email=email, phone=phone, status=status, address=address, cover=cover)
            
            return HttpResponseRedirect(reverse('portfolio:show_personal',
                args=(perso.pk,)))

    else:
        form = PersoForm()
    
    return render(request, 'home.html', {'form': form})

@login_required
def education(request, pk):
    u = request.user
    if request.method == 'POST':
        form = EducationForm(request.POST) 
        if form.is_valid():
            year = form.cleaned_data['year']
            title = form.cleaned_data['title']
            desc = form.cleaned_data['desc']
            
            education = u.education_set.create(year=year, title=title, desc=desc)
            return HttpResponseRedirect(reverse('portfolio:show_education',
                args=(education.pk,)))

    else:
        form = EducationForm()
    
    return render(request, 'education.html', {'form': form})


@login_required
def experience(request, pk):
    u = request.user
    if request.method == 'POST':
        form = ExperienceForm(request.POST) 
        if form.is_valid():
            year = form.cleaned_data['year']
            title = form.cleaned_data['title']
            desc = form.cleaned_data['desc']
            
            experience = u.experience_set.create(year=year, title=title, desc=desc)
            return HttpResponseRedirect(reverse('portfolio:show_experience',
                args=(experience.pk,)))

    else:
        form = ExperienceForm()
    
    return render(request, 'experience.html', {'form': form})


def show_personal(request, pk):
    form = get_object_or_404(Personal, pk=pk)
    return render(request, 'show_personal.html', {'form': form})


def show_education(request, pk):
    form = get_object_or_404(Education, pk=pk)
    return render(request, 'show_education.html', {'form': form})


def show_experience(request, pk):
    form = get_object_or_404(Experience, pk=pk)
    return render(request, 'show_experience.html', {'form': form})

def modify_perso(request, pk):
    perso = get_object_or_404(Personal, pk=pk)
    if request.method == 'POST':
        form = PersoForm(request.POST, instance=perso)
        if form.is_valid():
            perso = form.save()

            return HttpResponseRedirect(reverse('portfolio:show_personal',
                args=(perso.pk,)))

    else:
        form = PersoForm(instance=perso)
    
    return render(request, 'home.html', {'form': form})

def modify_education(request, pk):
    education = get_object_or_404(Education, pk=pk)
    if request.method == 'POST':
        form = EducationForm(request.POST, instance=education)
        if form.is_valid():
            education = form.save()

            return HttpResponseRedirect(reverse('portfolio:show',
                args=(education.pk,)))

    else:
        form = EducationForm(instance=education)
    
    return render(request, 'home.html', {'form': form})

def modify_experience(request, pk):
    experience = get_object_or_404(Experience, pk=pk)
    if request.method == 'POST':
        form = ExperienceForm(request.POST, instance=experience)
        if form.is_valid():
            experience = form.save()

            return HttpResponseRedirect(reverse('portfolio:show_experience',
                args=(experience.pk,)))

    else:
        form = ExperienceForm(instance=experience)
    
    return render(request, 'home.html', {'form': form})

def upload_picture(request):
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = ImageModel(pic=request.FILES['image'])
            newdoc.save()
            return HttpResponseRedirect(reverse('portfolio:last_step'))
    else:
        form = ImageUploadForm()
    
    return render(request, 'upload_picture.html', {'form': form})

def last_step(request):
    return render(request, 'last.html') 

def first_template(request):
    return render(request, 'resume.html')

portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,
initial-scale=1">
<title>Make your Portfolio</title>
<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/newbasic.css" rel="stylesheet">
</head>
<body class="body">
<div class="container-fluid">
    <div class="row">
        
        <div class="col-xs-8 left">
            <p></p>
        </div>
        {% block sign %} 

        <div class="col-xs-4 right">
        {% if user and not user.is_anonymous %}
        <h3>{{user.get_full_name|default:user.email}}</h3>
        <a class="btn" href="{% url 'portfolio:logout' %}">Log out</a>

        {% else %}
        <p>Have an account?</p>
        <a class="btn" href="{% url 'portfolio:login' %}">Sign In</a>
        </div>
        {% endif %}
        {% endblock %}
    </div>
    </div>
    {% block body %}
<div class="title">
    <p>Everything is design</p>
</div>
<div class="bottom">
    <div>
        <a href="{% url 'portfolio:perso'%}">Ready to build your Portfolio?</a>
</div>
</div>
{% endblock %}
</div>
</body>
</html>

portfolio/templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,
initial-scale=1">
<title>Make your Portfolio</title>
<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/newbasic.css" rel="stylesheet">
</head>
<body class="body">
<div class="container-fluid">
    <div class="row">
        
        <div class="col-xs-8 left">
            <p></p>
        </div>
   </div>
    </div>
    {% block body %}
<div class="title">
    <p>Everything is design</p>
</div>
<div class="bottom">
    <div class="jumbotron">
        <a href="{% url 'portfolio:home'%}">Ready to build your Portfolio?</a>
</div>
</div>
{% endblock %}
</div>
</body>
</html>

portfolio/templates/base2.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>My Title</title>
        <style type="text/css">
            @page {
                size: {{ pagesize }};
                margin: 1cm;
                @frame footer {
                    -pdf-frame-content: footerContent;
                    bottom: 0cm;
                    margin-left: 9cm;
                    margin-right: 9cm;
                    height: 1cm;
                }
            }
        </style>
    </head>
    <body>
        <div>
            {% for item in mylist %}
                RENDER MY CONTENT
            {% endfor %}
        </div>
        <div id="footerContent">
            {%block page_foot%}
                Page <pdf:pagenumber>
            {%endblock%}
        </div>
    </body>
</html>

portfolio/templates/education.html
{% extends 'home.html' %}
{% load widget_tweaks %}
                <h1>{% block header_text %}Education Information{% endblock %}</h1>

portfolio/templates/experience.html
{% extends 'home.html' %}
{% load widget_tweaks %}
                <h1>{% block header_text %}Experience Information{% endblock %}</h1>

portfolio/templates/home.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block body %}
<div class="container">
    <div id="form" class="col-md-6 col-md-offset-3 jumbotron">
        <div class="text-center">
                <h3>{% block header_text %}General Information{% endblock %}</h3>
        </div>
            <form method="POST">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                                <div class="form-group row">
                                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                        {{field|add_class:'form-control'}}
                                                {% for error in field.errors %}
                                                        <span class="help-block"> {{ error}} </span>
                                                {% endfor %}
                                </div>
                                                {% endfor %}
                                <div class="form-group">
                                        <button type="submit" class="btn btn-success">
                                        <span class="glyphicon glyphicon-ok"></span> Save
                                        </button>
                                        <a href="{% url 'portfolio:perso' %}" class="btn btn-default">Cancel</a>
                                </div>
           </form>

</div>
</div>
{% endblock %}

portfolio/templates/last.html
{% extends 'home.html' %}
{% load static %}
{% block body %}
<h3>{% block header_text %}Choose the template you wanna use for
        your resume{% endblock %}</h3>
<div class="first_template">
        <a href="{% url 'portfolio:first_template' %}">
                <img class="temp1" src=" {% static "temp1.png" %} "></img>
        </a>
</div>
{% endblock%}

portfolio/templates/login.html
{% extends 'base1.html'%}
{% load static %}
{% block signin %}

{% endblock %}
{% block body %}
<div>
        {% if user and not user.is_anonymous %}
        <li>
        <h1>{{ user.get_full_name|default:user.email}}</h1>
        </li>
        <li>
        <a class="btn" href="{% url 'portfolio:logout'%}">
                Log Out
        </a>
        </li>
        {% else %}
        <div class="container">
                <div class="row">
                        <div class="login-panel panel panel-default">
                                <div class="panel-body">
                                        <form method="POST">
                                                {% csrf_token %}
                                                {{form.as_p}}

                                                <input class="btn" type="submit"  value="login" />

                                        </form>
                                </div>
                                <div class="fb-login">
                                        <a href="{% url 'social:begin' 'facebook' %}">
                                                <img class="social-icn" src=" {% static "log-with-fb.png" %}">
                                                </img>
                                        </a>
                                </div>
                        </div>
                </div>
        </div>
        {% endif %}
</div>
{% endblock %}

portfolio/templates/resume.html
<html>
<head>
<title>Joe Bloggs - Curriculum Vitae</title>

<meta name="viewport" content="width=device-width"/>
<meta name="description" content="The Curriculum Vitae of Joe Bloggs."/>
<meta charset="UTF-8"> 

<link type="text/css" rel="stylesheet" href="/static/resume.css">
<link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700|Lato:400,300' rel='stylesheet' type='text/css'>

<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
</head>
<body id="top">
<div id="cv" class="instaFade">
	<div class="mainDetails">
		<div id="headshot" class="quickFade">
			<img src="/static/picture.jpg" alt="Alan Smith" />
		</div>
		
		<div id="name">
			<h1 class="quickFade delayTwo">Joe Bloggs</h1>
			<h2 class="quickFade delayThree">Job Title</h2>
		</div>
		
		<div id="contactDetails" class="quickFade delayFour">
			<ul>
				<li>e: <a href="mailto:joe@bloggs.com" target="_blank">joe@bloggs.com</a></li>
				<li>w: <a href="http://www.bloggs.com">www.bloggs.com</a></li>
				<li>m: 01234567890</li>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
	
	<div id="mainArea" class="quickFade delayFive">
		<section>
			<article>
				<div class="sectionTitle">
					<h1>Personal Profile</h1>
				</div>
				
				<div class="sectionContent">
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer dolor metus, interdum at scelerisque in, porta at lacus. Maecenas dapibus luctus cursus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies massa et erat luctus hendrerit. Curabitur non consequat enim. Vestibulum bibendum mattis dignissim. Proin id sapien quis libero interdum porttitor.</p>
				</div>
			</article>
			<div class="clear"></div>
		</section>
		
		
		<section>
			<div class="sectionTitle">
				<h1>Work Experience</h1>
			</div>
			
			<div class="sectionContent">
				<article>
					<h2>Job Title at Company</h2>
					<p class="subDetails">April 2011 - Present</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies massa et erat luctus hendrerit. Curabitur non consequat enim. Vestibulum bibendum mattis dignissim. Proin id sapien quis libero interdum porttitor.</p>
				</article>
				
				<article>
					<h2>Job Title at Company</h2>
					<p class="subDetails">Janruary 2007 - March 2011</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies massa et erat luctus hendrerit. Curabitur non consequat enim. Vestibulum bibendum mattis dignissim. Proin id sapien quis libero interdum porttitor.</p>
				</article>
				
				<article>
					<h2>Job Title at Company</h2>
					<p class="subDetails">October 2004 - December 2006</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies massa et erat luctus hendrerit. Curabitur non consequat enim. Vestibulum bibendum mattis dignissim. Proin id sapien quis libero interdum porttitor.</p>
				</article>
			</div>
			<div class="clear"></div>
		</section>
		
		
		<section>
			<div class="sectionTitle">
				<h1>Key Skills</h1>
			</div>
			
			<div class="sectionContent">
				<ul class="keySkills">
					<li>A Key Skill</li>
					<li>A Key Skill</li>
					<li>A Key Skill</li>
					<li>A Key Skill</li>
					<li>A Key Skill</li>
					<li>A Key Skill</li>
					<li>A Key Skill</li>
					<li>A Key Skill</li>
				</ul>
			</div>
			<div class="clear"></div>
		</section>
		
		
		<section>
			<div class="sectionTitle">
				<h1>Education</h1>
			</div>
			
			<div class="sectionContent">
				<article>
					<h2>College/University</h2>
					<p class="subDetails">Qualification</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies massa et erat luctus hendrerit. Curabitur non consequat enim.</p>
				</article>
				
				<article>
					<h2>College/University</h2>
					<p class="subDetails">Qualification</p>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec ultricies massa et erat luctus hendrerit. Curabitur non consequat enim.</p>
				</article>
			</div>
			<div class="clear"></div>
		</section>
		
	</div>
</div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-3753241-1");
pageTracker._initData();
pageTracker._trackPageview();
</script>
</body>
</html>

portfolio/templates/show_education.html
{% extends 'base.html'%}
{% load static %}
{% block body %}

<div class="col-md-6 col-md-offset-3 jumbotron">
        <div class="text-center">
<h1>Education Information You Entered</h1>

<ul class="list-group">
        <li class="list-group-item"> Year: {{form.year}} </li>
        <li class="list-group-item"> Title: {{form.title}} </li>
        <li class="list-group-item"> Description: {{form.desc}} </li>
        <a class="btn btn-default" href="{% url 'portfolio:modify_education' pk=form.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
<a class="btn btn-default" href="{% url 'portfolio:experience' pk=form.pk %}"><span class="glyphicon glyphicon-circle-arrow-right"></span></a>
</div>
</div>

</ul>
{% endblock %}

portfolio/templates/show_experience.html
{% extends 'base.html'%}
{% load static %}
{% block body %}

<div class="col-md-6 col-md-offset-3 jumbotron">
        <div class="text-center">
<h1>Experience Information You Entered</h1>

<ul class="list-group">
        <li class="list-group-item"> Year: {{form.year}} </li>
        <li class="list-group-item"> Title: {{form.title}} </li>
        <li class="list-group-item"> Description: {{form.desc}} </li>
        <a class="btn btn-default" href="{% url 'portfolio:modify_experience' pk=form.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
<a class="btn btn-default" href="{% url 'portfolio:upload_picture' %}"><span class="glyphicon glyphicon-circle-arrow-right"></span></a>
</div>
</div>

</ul>
{% endblock %}

portfolio/templates/show_personal.html
{% extends 'base.html'%}
{% load static %}
{% block body %}

<div class="col-md-6 col-md-offset-3 jumbotron">
        <div class="text-center">
<h1>Personal Information You Entered</h1>

<ul class="list-group">
        <li class="list-group-item"> Name: {{form.name}} </li>
        <li class="list-group-item"> Address: {{form.address}} </li>
        <li class="list-group-item"> Email: {{form.email}} </li>
        <li class="list-group-item"> Phone: {{form.phone}} </li>
        <li class="list-group-item"> Status: {{form.status}} </li>
        <li class="list-group-item"> Cover Letter: {{form.cover}} </li>
        <a class="btn btn-default" href="{% url 'portfolio:modify_perso' pk=form.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
<a class="btn btn-default" href="{% url 'portfolio:education' pk=form.pk %}"><span class="glyphicon glyphicon-circle-arrow-right"></span></a>
</div>
</div>

</ul>
{% endblock %}

portfolio/templates/upload_picture.html
{% extends 'home.html'%}
{% load static %}
{% block body %}

<h3>Upload your personal picture</h3>
<form action="{% url 'portfolio:upload_picture' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
        <input id="id_image" type="file" class="" name="image">
        </p>
        <input type="submit" value="submit">
</form>
{% endblock %}